# Site Settings
title: A Humble Developers Journal
email: david.mhernandez97@outlook.com
description: >
  A journal of a begnner hobbyist developer.
baseurl: "/personal-blog"
url: "http://mexdave1997.github.io"
twitter_username: MExcelms
github_username:  MEXdave1997
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM